#!/bin/bash
echo "Running... Kokomi build"
CURRENT_PATH=$(pwd)
mkdir ${CURRENT_PATH}/$1
OBJ_DIR=${CURRENT_PATH}/$1
SRC_DIR=~/dotfile
OBJECTS=${SRC_DIR}/Makefile
OBJECTS+=${SRC_DIR}/src/head.h
OBJECTS+=${SRC_DIR}/src/main.c


cd ${OBJ_DIR}
cp ${SRC_DIR}/Makefile .
cp ${SRC_DIR}/gitconfig ${OBJ_DIR}/.gitconfig
touch README.md
mkdir src
cd src
cp ${SRC_DIR}/src/head.h .
cp ${SRC_DIR}/src/main.c .

cd ..
git init .
git branch -M main
git add .
git commit -m "First commit"

echo "\\--------------------------\\"
echo " \\---                    ---\\"
echo "  \\--     Everything Done  --\\"
echo "   \\---                    ---\\"
echo "    \\--------------------------\\"

